language: java
jdk:
- oraclejdk8
sudo: required
dist: trusty
install: gradle/installViaTravis.sh
script: gradle/buildViaTravis.sh
before_cache: gradle/prepCaches.sh
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: TOjXTk0g2VALPJ/HAlLUdUEeKZnq873egV6WTyK77VeqUWqp+oz0s8oV/5p99Oz8Gsa5RFmJG7IjXYM7c83uL/xRUxZYZbanB2TUgA7iMdLVX+9YCM78Jzb9zMOXmyLLaYmXIdIRlG+wOeRKK9GZkWW8jCLlnTTIOE71EVqeAFb5Aee4GzYI/OYg99zRVylQKkOX7fclOiY7uIapKj07dt4fFw+h97UcOL4Lu61dOuAf3zNnrzzz4Xp5sMZFbz0/3QOQwY+vWR2szYBWQGRVKR51TtrzsdBO+D9Q4GbsXctlJXW2N6DKwx9l5s2jwHPHoNv7uaZxkVX7YXj27wVjx+uDftO0VK/6QbG4hOZPAkxPfwWUFaptO7mpyqPBRrw5yoo1qbdsMLjI+BnixJ6JQIi6PJWfygH2g4hc7OWiwzN59FEI11Gr8ZwRv/DdCCNOm5qIMPdzbC9xTcUN2pmNprUVj9oUHjSjNOnL2oJMYNrcc2xBavCXWjrdx7sqDc3OxEbK51clwUq3l+EJDq+0LfC4trpAi9MGiS7vDPslANFlKILvJHlKFf4mU76WwIPOYR6vOsbmu8pTdYsf8buQv65xBfA3g2wZbAiHIHBlvTaO7xIxhXSetd8vfiGvDdbqzScwQKQ77adekCJSaLbqWcOoMH4Eomv/bKZ9jPtKLLI=
  - secure: FRLG0/ccG3juTut+vwoUGfbuwmW2UXYsHWQoAonZEzz9Wo8u60v96kjsoYl1aSsNf9+TQR9ZRk+2BGeN47mTdpEeyt0+2+lWz1LEVq/tkUMVxnvKud9eV1NBP9JqloU1+IbcgSZlqQrrl1oI8J7ZdZzPCzAt5+jYBhoxAFhUzy426hdJxt67E8gROPnsmcmItCPsDdqcg9fFaY6wb89VhiEv7qO4ZIZMLfBoWATESDoD7P0dFOYgWLm/GyjNaF68wW6Pgg5n/UosY4c8HaemktXwgcFfrhcLpvu4Qs6cacNgd6oh1S1wHaAetQlWghhb3k9Iw0qGyus1HrF5hgN7G3IS7CWi/+TM+0444ZUFiCte/UP+J+2MJqIjR3SYim37Zxxdwcmc8qlzZD2Zmsq0xFNiDAZaQn4mQrvnWMbIKrBifov+2ytGCb2opaGQlk0piDWFrmphcleyYZaxDmULL1gqJANgnYW3Sw0Y9hmE3s4F/WxQhuo7UjNzaOrewUg5T6WTDOEDA5bVqPE14sOT9oljWQP84LtpMpwOpQm86dfeNS8Cd2p9oQwzCyTWJjK819iGIRAMAiJDAP0AmZBeq2skCUfDYwV0dPYLG+myy26IOEDSA4YyIjVnonoDOXe8Wc7L9U/NupI9pzhxzOYaoh2TjQ3l0bFVHREBhnCXreA=
