language: java
jdk:
- oraclejdk8
dist: trusty
sudo: false
install: gradle/installViaTravis.sh
script: gradle/buildViaTravis.sh
before_cache: gradle/prepCaches.sh
cache:
  directories:
  - $HOME/.gradle
env:
  global:
  - secure: "TAMa1t13eHsTC3mYoSyjq2A/Ty4klhKLoqLsrNZXQegGRRXlGWfsU97p+Msu8a3T8BT50KP45EziaA6j5m42hZdtIizcw6gjjUiJOcwxXhxb+C/uBU0Ym0TsW7lkmCJWPudWtZ6U5Y78g2+ZqZQARE7VOacKOc4RDHYEe1vAHvJD90t4pRBrtggl+Aajcay7XktnRlqf6eKj19+4bzPo/GWc+4fibRb/OIirkM5NRakuUEWKFaQbYzL85438EaB0WzcQYUoXUt/RUwKvtLnSBg2xvcOU/p79kK/vbAoB4DU1XqRouvNieUccNEGNZjhc94GERtxh1QFp2xqD6poMSNx4dzwzayaOqDuen6iVVGH3+CKsXrpjxuLfxIUBKh4u6gahrYkuZrXaVR6vEJDzI9xyPTSWqzZHgOxYrDzxEkYt9pPAaR7oQDqR56PnFYaMrtZdZ7MrTkH4A5VplKqPRrk6ucUTWZj5AMCUaadlBPpophEgVsmu+Rm+mnMkS1SIj7rf6rSZYynfsKURA8r4WBMfepFuJO0hUwlNrshQN9EqVI7Q/BrEnjnveo59YBGeat4vTNwHTRr6YVpNe8kWh/mWeJyaq8Cb8yu02nUst7kFjTYvJZVrVz+t1T2UnrKAbJ5yr8FzZzTRrS57Dt5VLaQrnOBwyRxUu393qHLO/FM="
  - secure: "BHRyu5TgFtEhopBFvkSgsmPg4viCqgV/W+DGqzHkZuz9x/8fBJFGuz8vn8FwBBNRlm6fHzedLGz8VU9zL87ZDU8wVcEOPKFuboGzCsQmm75R2JoUMb/nZ+Sk+9pQoP39ZTlIWN0Rl0ZQEMyRKPuEMWiKHjRYopRUKVD+Fvuac8aLt0ILAsCyyK2nxzQPLIacxXYSLb2mhcZIexkiPOLjrxyGDMX+v9d++bN2VhBNJD0zQ+SC5fedsMahpS1Qs0Mqn0Yq15N9AS83mwHx8ACxzdLBAqf0U4RIDTg1dmIixsPCPxRYCqrNu6t2+IbcdmAxJIYLmc1YEherKxefcSkmX1J9KBQf1FjJUKgZZqYQ4AHJB/b9Lc1Yj9TXjNkKRMWv3Cpara29+P9i7e9f98JLr/nnp6xEYaPTbNzZ76zfQk8oPCYVJSi0xZ+A7CV7UfKAf0EAhLLDYUN/k2bFF13SiAIFApiwhR2pPak2EnNQeAxr2RrmgFPMLjVTP9R9VdKUr4d0pCd3IT9WfX2rJMGA/p0PE9MZLTejwUTpO9CVCD4yuTn5s8LibAfLVCdrk+GVzmXZ9XVc/WojwUwHkH0EecNJ+7klE5lReED5ldd90O/X1/YnTwINlQJ4O7bvOJQM/QzNMspiW7dDpXVdjVNOR1MWzeF/wt13VRpOamM66wk="
