language: java
jdk:
- oraclejdk8
sudo: false
script: gradle/buildViaTravis.sh
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
env:
  global:
  - secure: f+8hQxOR3qzrhqmmFvmn3K0ozK9SYL241HdpsWcO8VDupHe29KrLGpIiOP0Hz71vb6q2WZHJzqLtXxxX8RUTNV2VL/sn08d9j6zzCtdvcKrUTRYG0sr/uZV7Oep1vo2KgX2eeI5nFndm536r1sElwvA1MwXRmfpo/IGrcN/NIHlSMQqWxZdPFYeit2vL+hwgTm8D2R04PkPwIYqutph3WiSpI44Au/WbZLLOoM0BC7H14p89KR8/0jGnqMANbTSMmGXJw+P6gd+4hpC66I17pYXXsAVnYVrJxPKqhWuhpFj30bo6H7I3OHHriSEIalw9WcHDoTiROwa6tp3FHjzncfS88RW0JPxrUMInaNZPv8u+7wz98hoUgYrhU/4/7xUh9RZGKpVmv5EjQ6tTe8K4H+0g12vucXw64WkRJgVQUncTRwx33y5SLVTf41ADhcR5rglm0LVainpuHp69mg9uKG/PRwf9l2wIJvbhKGL4A3nJ8M2w+4W4o6VzgZI+Nw+ntbInp2A3aW0Y+CLG3a/QtJcxJT+TdNtTs/GBcwvnkYpzG7DyMQufNWZO8+dtpDckGVRL6h8jAbiuN2OJGjqeZNMssr8DlE37irX/afCtFgzQTGtQ5txm3lHdbPFr1BOHCax7Z/BOdtXokgBLeEa67BIKEY6JIubR17Vm9U1Up8M=
  - secure: mMI0nRr8PViTs35d+ok3NmgmnYQLp0PF1AB8rBMe7B0x22AAG7r7YkgexARQzIjK17ij4HW6IlsXEXUMAhwaSxBSUAzmEhRfd9QRuBRh3kS+HfUc/Xin+G85I9u0bYk5U38OA0YxsFTfOPxLv1vu8WlpZ34MAOwqVBRLtCUxOdBA5vHnTUsDv8ZQEDEZhwyBy1DWy6p95tGDQixSqRzXvQgDCXkTaWVDFLcAvAtOSpxAsg36S6XpsH9+v2WWxVNst2PQqZrXix65xxV+A11JN7KHUYdj1JtqKq4KanDjBr8PJW3rvRFPntC0yb7I/QblhTVVpWHi2j2V3aRLDoG/HUpBC/KTFlTOHJFxYYXGDYtqDc9Kmjk72d95O8FxL0hcDs+m79WKrXDm0O9VVhVct0uq0jbYORHiYx+AubqMlazuNWEmVKkoYRIj1B3gK/5urePS2l+7And0EOi7z2GBmxni8mZTJlPPnpLQUHG7fcmX3Eo7MN4OQCznnqaSgky3HlNcXW0y1uRQ5YqDG9uJH1UuQPxdLu59Ws1XGmuXU2JdTBCGjk4S9YiHdrsdijW4iybwXL7rqU5ngMcIO+lkAueokHLCMeXMLMyN3Ib34oA3xt0nQdcGAW+Q8Yhs3VLEkYaIfWDKjL02uhQYGLuWNTftYX6KoUo1O8jzokGBM2w=
