spinnaker:
  cassandra:
    cluster: 'spinnaker'
    keyspace: 'echo'
netflix:
  appinfo:
    name: 'echo-core'
search:
  index: 'event_history'
# server:
  # port: 8120

kafka:
  prefix: 'suro'
  hostname: 'echo.prod.netflix.com'
  app: 'spinnaker'
  rowid: 'events'
