name: Candidate release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Candidate build
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          GRADLE_OPTS: -Xmx6g -Xms6g -Dorg.gradle.daemon=false
        run: |
          ./gradlew -PenablePublishing=true --info -Prelease.disableGitChecks=true -Prelease.useLastTag=true -PbintrayUser="${BINTRAY_USER}" -PbintrayKey="${BINTRAY_API_KEY}" candidate
      - name: Get the changelog
        id: get_changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          . .github/workflows/release_info.sh ${{ github.event.repository.name }}
          echo ::set-output name=CHANGELOG::$(echo -e "${CHANGELOG}")
          echo ::set-output name=SKIP_RELEASE::${SKIP_RELEASE}
      - name: Create release
        if: steps.get_changelog.outputs.SKIP_RELEASE == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
           tag_name: ${{ github.ref }}
           release_name: ${{ github.event.repository.name }} ${{ github.ref }}
           body: |
            ${{ steps.get_changelog.outputs.CHANGELOG }}
           draft: false
           prerelease: true