server:
  port: 8084

services:
  orca:
    baseUrl: http://localhost:8083
  front50:
    baseUrl: http://localhost:8080
  clouddriver:
    baseUrl: http://localhost:7002
#optional services:
  echo:
    enabled: false
  flapjack:
    enabled: false
  igor:
    enabled: false
  mahe:
    enabled: false

redis:
  connection: redis://localhost:6379

swagger:
  enabled: true
  title: Spinnaker API
  description:
  contact:
  patterns:
    - .*tasks.*
    - .*applications.*
    - .*securityGroups.*
    - /search
    - .*pipelines.*
    - .*loadBalancers.*
    - .*instances.*
    - .*images.*
    - .*elasticIps.*
    - .*credentials.*
    - .*events.*
    - .*builds.*
    - .*instanceTypes.*
    - .*vpcs.*
    - .*subnets.*
    - .*networks.*
