#
# Copyright 2014 Netflix, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

server:
  port: 8501

bastion:
  enabled: false

aws:
  enabled: ${AWS_ENABLED:false}
  defaults:
    instanceClassBlockDevices:
      - instanceClass: m3
        blockDevices:
          - deviceName: /dev/sdb
            virtualName: ephemeral0
          - deviceName: /dev/sdc
            virtualName: ephemeral1

gce:
  enabled: ${GCE_ENABLED:false}
  defaults:
    instanceTypePersistentDisks:
    - instanceType: n1-standard-1
      persistentDisk:
        type: pd-ssd
        size: 20
    - instanceType: n1-standard-2
      persistentDisk:
        type: pd-ssd
        size: 40
    - instanceType: n1-standard-4
      persistentDisk:
        type: pd-ssd
        size: 80
    - instanceType: n1-standard-8
      persistentDisk:
        type: pd-ssd
        size: 160
    - instanceType: n1-standard-16
      persistentDisk:
        type: pd-ssd
        size: 320
    - instanceType: f1-micro
      persistentDisk:
        type: pd-standard
        size: 10
    - instanceType: g1-small
      persistentDisk:
        type: pd-standard
        size: 10
    - instanceType: n1-highmem-2
      persistentDisk:
        type: pd-ssd
        size: 40
    - instanceType: n1-highmem-4
      persistentDisk:
        type: pd-ssd
        size: 80
    - instanceType: n1-highmem-8
      persistentDisk:
        type: pd-ssd
        size: 160
    - instanceType: n1-highmem-16
      persistentDisk:
        type: pd-ssd
        size: 320
    - instanceType: n1-highcpu-2
      persistentDisk:
        type: pd-ssd
        size: 40
    - instanceType: n1-highcpu-4
      persistentDisk:
        type: pd-ssd
        size: 80
    - instanceType: n1-highcpu-8
      persistentDisk:
        type: pd-ssd
        size: 160
    - instanceType: n1-highcpu-16
      persistentDisk:
        type: pd-ssd
        size: 320
    - instanceType: default
      persistentDisk:
        type: pd-standard
        size: 100

docker:
  enabled: ${DOCKER_ENABLED:false}

titan:
  enabled: ${TITAN_ENABLED:false}
