netflix:
  appinfo:
    name: 'igor'

jenkins:
  masters:
    -
      name: 'jenkins1'
      address: 'http://jenkins.example.com/'
      username: 'username'
      password: 'password'


spinnaker:
  build:
    pollInterval: 30
