redis:
  enabled: true
  host: ${REDIS_HOST:localhost}

server:
  port: 8081

bastion:
  enabled: false

aws:
  enabled: ${AWS_ENABLED:false}

gce:
  enabled: ${GCE_ENABLED:false}

docker:
  enabled: ${DOCKER_ENABLED:false}

titan:
  enabled: ${TITAN_ENABLED:false}
