server:
  port: 8083

oort:
  baseUrl: http://localhost:8081
front50:
  baseUrl: http://front50-${netflix.stack}.${netflix.environment}.netflix.net
mort:
  baseUrl: http://localhost:8082
kato:
  baseUrl: http://localhost:8501

redis:
  connection: redis://localhost:6379

