server:
  port: 8083

default:
  bake:
    account: default

front50:
  baseUrl: http://localhost:8080
tide:
  baseUrl: http://localhost:8090
oort:
  baseUrl: http://localhost:7002
mort:
  baseUrl: http://localhost:7002
kato:
  baseUrl: http://localhost:7002
echo:
  enabled: false
bakery:
  baseUrl: http://localhost:8089

redis:
  connection: ${REDIS_URL:redis://localhost:6379}

tasks:
  useWaitForAllNetflixAWSInstancesDownTask: false

