server:
  port: 8083

front50:
  baseUrl: http://localhost:8080
tide:
  baseUrl: http://localhost:8090
oort:
  baseUrl: http://localhost:8081
mort:
  baseUrl: http://localhost:8082
kato:
  baseUrl: http://localhost:8501
echo:
  enabled: false
bakery:
  baseUrl: http://localhost:8089

redis:
  connection: ${REDIS_URL:redis://localhost:6379}

tasks:
  useWaitForAllNetflixAWSInstancesDownTask: false
