server:
  port: 8080

aws:
  defaultSimpleDBDomain: CLOUD_REGISTRY
  simpleDBEnabled: false

spinnaker:
  cassandra:
    enabled: true
    cluster: CASS_SPINNAKER
    keyspace: front50
    name: default
