server:
  port: 8080

aws:
  defaultSimpleDBDomain: CLOUD_REGISTRY
  simpleDBEnabled: false

google:
  enabled: ${GOOGLE_ENABLED:false}

spinnaker:
  cassandra:
    enabled: ${SPINNAKER_CASSANDRA_ENABLED:true}
    cluster: CASS_SPINNAKER
    keyspace: front50
    name: default
