server:
  port: 8087

rush:
  baseUrl: http://localhost:8085
  # TODO(duftler): Figure out the right way to set this dynamically.
  configDir: /Users/duftler/spinnaker/rosco/rosco-web/config/packer

executionStatusToBakeStates:
  associations:
    - executionStatus: PREPARING
      bakeState: PENDING
    - executionStatus: FETCHING_IMAGE
      bakeState: PENDING
    - executionStatus: RUNNING
      bakeState: RUNNING
    - executionStatus: CANCELED
      bakeState: CANCELED
    - executionStatus: SUCCESSFUL
      bakeState: COMPLETED
    - executionStatus: FAILED
      bakeState: CANCELED

executionStatusToBakeResults:
  associations:
    - executionStatus: SUCCESSFUL
      bakeResult: SUCCESS
    - executionStatus: FAILED
      bakeResult: FAILURE

debianRepository: http://dl.bintray.com/spinnaker/ospackages ./

defaultCloudProviderType: aws

aws:
  enabled: ${AWS_ENABLED:false}
  bakeryDefaults:
    # TODO(duftler): Make aws credentials-handling consistent with that of other spinnaker modules.
    # TODO(duftler): Externalize this into a credentials block.
    awsAccessKey: ${AWS_ACCESS_KEY:FOO}
    awsSecretKey: ${AWS_SECRET_KEY:BAR}
    templateFile: aws-ebs.json
    defaultVirtualizationType: hvm
    operatingSystemVirtualizationSettings:
    # TODO(duftler): Identify proper base amis.
    # TODO(duftler): Support additional store types beyond ebs.
    # TODO(duftler): Support additional operating systems.
    - os: ubuntu
      virtualizationSettings:
      - region: us-east-1
        virtualizationType: hvm
        instanceType: t2.micro
        sourceAmi: ami-d4aed0bc
        sshUserName: ubuntu
      - region: us-east-1
        virtualizationType: pv
        instanceType: m3.medium
        sourceAmi: ami-8007b2e8
        sshUserName: ubuntu
    - os: trusty
      virtualizationSettings:
      - region: us-east-1
        virtualizationType: hvm
        instanceType: t2.micro
        sourceAmi: ami-9eaa1cf6
        sshUserName: ubuntu
      - region: us-east-1
        virtualizationType: pv
        instanceType: m3.medium
        sourceAmi: ami-98aa1cf0
        sshUserName: ubuntu

docker:
  enabled: ${DOCKER_ENABLED:false}
  bakeryDefaults:
    targetRepository: ${DOCKER_TARGET_REPOSITORY:}
    templateFile: docker.json
    operatingSystemVirtualizationSettings:
    - os: ubuntu
      virtualizationSettings:
        sourceImage: ubuntu:precise
    - os: trusty
      virtualizationSettings:
        sourceImage: ubuntu:trusty

google:
  enabled: ${GOOGLE_ENABLED:false}
  gce:
    bakeryDefaults:
      # TODO(duftler): Externalize this into a credentials block.
      project: shared-spinnaker
      zone: us-central1-f
      templateFile: gce.json
      operatingSystemVirtualizationSettings:
      - os: ubuntu
        virtualizationSettings:
          sourceImage: ubuntu-1204-precise-v20141212
      - os: trusty
        virtualizationSettings:
          sourceImage: ubuntu-1404-trusty-v20141212

swagger:
  enabled: true
  title: Spinnaker Rosco API
  description:
  contact:
  patterns:
    - .*api/v1.*
